### ISSUE TITLE
Update Assignment 2B

### ISSUE THREAD

**Issue by cwhite911** [ncsu-geoforall-lab/gis-584-uas-course#1]
The instructions for Assignment 2B are outdated. We either need to update the materials for use with Agisoft Metashape 2.1.4 or convert the content to use WebODM.

https://github.com/ncsu-geoforall-lab/gis-584-uas-course/blob/main/course/topics/topic_2_sfm/assignments/assignment_2b.qmd

**Comment by Pratikshya-Regmi** [comment]
I updated the required changes. Now , it should work on Agisoft Metashape 2.1.2 .

**Comment by cwhite911** [comment]
Awesome! I'll check it out.
